-- 0001_init — начальная схема микросервиса users.
--
-- Миграции лежат в репозитории сервиса, а не в отдельном «репозитории БД».
-- Причина: схема — часть контракта сервиса. Код и схема должны выкатываться
-- из одной кодовой базы (Фактор 1) и одной ревизии, иначе неизбежна ситуация
-- «код новый, таблицы старые».

CREATE TABLE IF NOT EXISTS users (
    -- GENERATED BY DEFAULT AS IDENTITY, а не BIGSERIAL.
    -- SERIAL — это наследие: он создаёт отдельную sequence, которая
    -- «не принадлежит» колонке по стандарту SQL, из-за чего права и
    -- переносимость ведут себя неочевидно. IDENTITY — стандартный способ
    -- начиная с PostgreSQL 10. BY DEFAULT (а не ALWAYS), чтобы можно было
    -- вставить явный id при восстановлении дампа.
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id BIGINT UNIQUE,
    name        TEXT        NOT NULL,
    -- email NOT NULL DEFAULT '' вместо nullable.
    -- Почему: NULL и пустая строка — два разных «нет значения», и код
    -- вынужден обрабатывать оба. Если бизнес-смысла в различии нет,
    -- дешевле запретить NULL на уровне схемы.
    email       TEXT        NOT NULL DEFAULT '',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Индекс на telegram_id создаётся автоматически ограничением UNIQUE —
-- отдельный CREATE INDEX был бы дублем.

CREATE TABLE IF NOT EXISTS mood_answers (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- ON DELETE CASCADE: удалили пользователя — уехали и его ответы.
    -- Альтернатива (RESTRICT) означала бы, что DELETE /users/:id падает,
    -- пока есть ответы. Для этого приложения каскад честнее.
    user_id    BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    question   TEXT        NOT NULL,
    answer     TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Составной индекс под главный запрос «последние ответы пользователя».
-- Порядок колонок важен: (user_id, created_at DESC) обслуживает
-- и фильтр по user_id, и сортировку; обратный порядок — только сортировку.
CREATE INDEX IF NOT EXISTS mood_answers_user_created_idx
    ON mood_answers (user_id, created_at DESC);
